name: Build and Release Windows Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Executable
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile phone_number_capture.py
        shell: cmd

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: PhoneNumberCaptureExecutable
          path: ./dist/phone_number_capture.exe

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: PhoneNumberCaptureExecutable

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: PhoneNumberCaptureExecutable/phone_number_capture.exe
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ github.ref }}
          body: |
            Automated release of the latest executable.
